# .github/
#      workflows/
#              main.yml
name: test-github-acion-cicd         # workflow 이름
on: push                             # event trigger on push

jobs:
  build:                             # job id
    name: test-build                 # job 이름
    runs-on: ubuntu-latest           # 가상 환경
    steps:
    - name: checkout source             # step 이름
      uses: actions/checkout@master     # 소스코드 checkout
    - name: test-step01                 # step 이름
      run: echo "im test-step01"        # linux command 실행
    - name: test-step02                 # step 이름
      run: echo "im test-step02"        # linux command 실행
